##### 1. Создайте одномерный массив из чисел от 1 до 10. Затем преобразуйте его в двумерный массив 2x5. Найдите сумму всех элементов массива, а также среднее арифметическое.

In [15]:
import numpy as np

arr = np.arange(1, 11)
print(arr)
new_arr = arr.reshape(2, 5)
print(new_arr)
print(arr.sum(), arr.mean())

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
55 5.5


##### 2. Создайте матрицу размером 5x5, содержащую числа от 1 до 25. Извлеките из неё:
1. Первый столбец
2. Последние три элемента второй строки
3. Центральный элемент массива

In [29]:
mat = np.arange(1, 26).reshape(5, 5)
print(mat[0])
print(mat[1,:3])
i, j = mat.shape
print(mat[i // 2, j // 2])

[1 2 3 4 5]
[6 7 8]
13


##### 3. Создайте массив из 20 случайных чисел. Найдите:
1. Минимальное и максимальное значения
2. Медиану
3. Стандартное отклонение

In [ ]:
arr = np.random.randint(10, size=20)
print(f"min - {arr.min()}, max - {arr.max()}")
print(f"median - {np.median(arr)}")
print(f"std - {arr.std()}")

min - 0, max - 9
median - 4.5
sco - 3.108054053584011


##### 4. Создайте массив случайных чисел от 0 до 100 (10 элементов). Определите, какие из них чётные. Замените все нечётные элементы на 0.

In [77]:
arr = np.random.randint(100, size=10)
print(arr)
for i, a in enumerate(arr):
    if a % 2 == 0:
        print(a, end=" ")
    else:
        arr[i] = 0
print()
print(arr)

[51 82 25 83 23 76 93 83 73 46]
82 76 46 
[ 0 82  0  0  0 76  0  0  0 46]


##### 5.1 Создайте матрицу произвольного размера. 
1. Найдите транспонированную матрицу.
2. Найдите обратную матрицу, если это возможно.
3. Найдите собственные значения и собственные вектора.

In [83]:
from numpy import linalg
mat = np.arange(1, 26).reshape(5, 5)
print(mat.T)
print(linalg.inv(mat) if linalg.det(mat) != 0 else "singular")
print(linalg.eig(mat))

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
singular
EigResult(eigenvalues=array([ 6.86420807e+01+0.00000000e+00j, -3.64208074e+00+0.00000000e+00j,
       -2.90915693e-15+2.38171334e-15j, -2.90915693e-15-2.38171334e-15j,
        1.97408863e-16+0.00000000e+00j]), eigenvectors=array([[-0.10797496+0.j        ,  0.67495283+0.j        ,
         0.14670174+0.1909791j ,  0.14670174-0.1909791j ,
        -0.07390125+0.j        ],
       [-0.25277499+0.j        ,  0.3603897 +0.j        ,
         0.3294084 -0.26685261j,  0.3294084 +0.26685261j,
        -0.19697337+0.j        ],
       [-0.39757502+0.j        ,  0.04582657+0.j        ,
        -0.59267376+0.j        , -0.59267376-0.j        ,
         0.74972491+0.j        ],
       [-0.54237506+0.j        , -0.26873656+0.j        ,
        -0.38968465+0.03664144j, -0.38968465-0.03664144j,
        -0.61292471+0.j        ],
       [-0.68717509+0.j        , -0.58329969+0.j        ,
         0.50624827

##### 5.2 Создайте две матрицы 4x4, заполненные случайными числами. Выполните следующие операции:

1. Найдите их матричное произведение.
2. Объедините две матрицы в тензор/в одну матрицу 4x8.

In [198]:
mat1 = np.random.randint(100, size=(4, 4))
mat2 = np.random.randint(100, size=(4, 4))
mat3 = mat1.dot(mat2)
print(mat3)
mat4 = np.hstack((mat1, mat2)) # 4x8
print(mat4)
mat5 = np.dstack((mat1, mat2))
print(mat5)

[[10908  7291  9054 15070]
 [ 9003 12053  7458 10786]
 [ 5230  3360  2931  6260]
 [ 7380  3731  3517  5927]]
[[72  8 58 93 10 50 66 83]
 [33 86 47 81  0 93 21  2]
 [10 21 16 57 57 46 36  9]
 [ 1 11 54 58 74  3 22 92]]
[[[72 10]
  [ 8 50]
  [58 66]
  [93 83]]

 [[33  0]
  [86 93]
  [47 21]
  [81  2]]

 [[10 57]
  [21 46]
  [16 36]
  [57  9]]

 [[ 1 74]
  [11  3]
  [54 22]
  [58 92]]]


##### 6. Создайте трёхмерный массив размером 3x3x3, заполненный случайными числами. Выполните следующие операции:
1. Найдите сумму элементов по каждой оси.
2. Найдите минимальный элемент для каждого слоя.
3. Отсортируйте каждый слой по возрастанию.

In [139]:
tensor = np.random.randint(100, size=(3, 3, 3))

print(tensor)

for a in range (tensor.ndim):
    print(f"axis - {a}, sum - \n {np.sum(tensor, axis=a)}")

for a in range (tensor.ndim):
    print(f"layer - {a}, min - {tensor[a].min()}")

[[[ 7 53 95]
  [58 56 81]
  [79 26 25]]

 [[ 0 52 40]
  [ 4 80 27]
  [58 53 88]]

 [[24 39 76]
  [74 85 59]
  [64 99 29]]]
axis - 0, sum - 
 [[ 31 144 211]
 [136 221 167]
 [201 178 142]]
axis - 1, sum - 
 [[144 135 201]
 [ 62 185 155]
 [162 223 164]]
axis - 2, sum - 
 [[155 195 130]
 [ 92 111 199]
 [139 218 192]]
layer - 0, min - 7
layer - 1, min - 0
layer - 2, min - 24


##### 7. Сгенерируйте набор данных из 100 случайных точек в 3D-пространстве. Выполните их нормализацию (приведите к единичному масштабу) по каждой оси.

In [ ]:
points = np.random.randint(100, size=(100, 3))
min_vals = points.min()
max_vals = points.max()

normalized_points = (points - min_vals) / (max_vals - min_vals)
normalized_points

array([[0.71428571, 0.02040816, 0.        ],
       [0.59183673, 0.5       , 0.89795918],
       [0.06122449, 0.78571429, 0.80612245],
       [0.03061224, 0.13265306, 0.7755102 ],
       [0.12244898, 0.13265306, 0.83673469],
       [0.84693878, 0.5       , 0.34693878],
       [0.62244898, 0.57142857, 0.65306122],
       [0.75510204, 0.1122449 , 0.97959184],
       [0.76530612, 0.43877551, 0.26530612],
       [0.24489796, 0.5       , 0.89795918],
       [0.08163265, 0.28571429, 0.65306122],
       [0.76530612, 0.32653061, 0.05102041],
       [0.44897959, 0.93877551, 0.15306122],
       [0.26530612, 0.06122449, 0.54081633],
       [0.96938776, 1.        , 0.01020408],
       [0.80612245, 0.6122449 , 0.58163265],
       [0.89795918, 0.84693878, 0.86734694],
       [0.        , 0.20408163, 0.5       ],
       [0.20408163, 0.2755102 , 1.        ],
       [0.13265306, 0.82653061, 0.37755102],
       [0.19387755, 0.89795918, 0.01020408],
       [0.01020408, 0.12244898, 0.84693878],
       [0.

##### 8*. Загрузите любое изображение (в рамках приличия, конечно) и сожмите его с помощью сингулярного разложения (SVD). Выберете разное количество сингулярных значений и сравните полученный результат с оригиналом.

In [193]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

img = Image.open("data/background_nebula.png").convert("L")  # "L" для преобразования в оттенки серого
img_array = np.array(img)

np.linalg.svd(img_array, full_matrices=False)

KeyboardInterrupt: 